### ISSUE TITLE
Create a CHANGELOG

### ISSUE THREAD

**Issue by philss** [magnetis/caze#5]
It's important to give information about what changed in the history of the project.
We can follow the [Keep a CHANGELOG](http://keepachangelog.com/) style that is very interesting.

**Comment by brunojabs** [comment]
@philss, @bezelga, @Lucasosf, @luizParreira I think we already have a changelog, can we close this issue?

**Comment by philss** [comment]
@brunojabs hum, yeah! I almost forgot this. I'm closing.
